doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        'App\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Infrastructure/Doctrine/Migrations'
